version: "3"

services:
  app:
    image: node:16-alpine
    command: sh -c "cd ./frontend && npm i && npm run build && cd .. && npm i && npm run build && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: converter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: converter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
